# Generated by Django 2.1.5 on 2019-01-30 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=1000)),
                ('mentions', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField(verbose_name='DATE COMMENTED')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(verbose_name='DATE LIKED')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=1000)),
                ('post_description', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=1000)),
                ('mentions', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField(verbose_name='DATE CREATED')),
                ('likes', models.IntegerField(default=0)),
                ('flags', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('num_followers', models.IntegerField(default=0)),
                ('num_following', models.IntegerField(default=1)),
                ('followers', models.CharField(max_length=1000)),
                ('following', models.CharField(max_length=1000)),
                ('join_date', models.DateTimeField(verbose_name='DATE JOINED')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainFeed.User'),
        ),
        migrations.AddField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainFeed.User'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainFeed.Post'),
        ),
        migrations.AddField(
            model_name='flag',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainFeed.User'),
        ),
        migrations.AddField(
            model_name='flag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainFeed.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainFeed.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainFeed.Post'),
        ),
    ]
